language: shell

sudo: required

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

before_install:
    - mkdir "$HOME/bin"
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        dlurl='https://anonscm.debian.org/cgit/collab-maint/devscripts.git/plain/scripts/checkbashisms.pl'
        sudo curl "$dlurl" > "$HOME/checkbashisms"
        chmod u+x "$HOME/checkbashisms"
        mv "$HOME/checkbashisms" "$HOME/bin"
      fi
    - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update
        brew install shellcheck checkbashisms
      fi

script:
    - export PATH="$PATH:~/bin"
    - ./lint
    - ./test
    - ./setup -d "$HOME/bin" -p "$HOME/.goat"
    - . ~/.bashrc
    - TEST_PATH="$PWD/.goat" ./test

os:
  - linux
  - osx

matrix:
  fast_finish: true

notifications:
  email: false
