language: shell

sudo: required

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo curl 'https://anonscm.debian.org/cgit/collab-maint/devscripts.git/plain/scripts/checkbashisms.pl' > checkbashisms; chmod u+x checkbashisms; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck checkbashisms; fi

script:
    - PATH="$PATH:." ./lint
    - PATH="$PATH:." GOAT_PATH= ./test
    - ./setup -d "$PWD/.goat"
    - . ~/.bashrc
    - PATH="$PATH:." GOAT_PATH="$PWD/.goat" ./test

os:
  - linux
  - osx

matrix:
  fast_finish: true

notifications:
  email: false
