#!/bin/sh
#
# lint - Test POSIX complience and quality with checkbashisms and shellcheck.
#
# Usage: ./lint

gEXIT_STATUS='0'

shellcheck --shell=sh ./target/goat.sh || gEXIT_STATUS='1'
shellcheck --shell=sh ./target/leash.sh || gEXIT_STATUS='1'
shellcheck --shell=sh --external-sources ./goatherd.config ./goatherd || gEXIT_STATUS='1'

checkbashisms -npfx ./target/goat.sh || gEXIT_STATUS='1'
checkbashisms -npfx ./target/leash.sh || gEXIT_STATUS='1'
checkbashisms -npfx ./goatherd || gEXIT_STATUS='1'

exit "$gEXIT_STATUS"
