#!/bin/sh
#
# lint - Test POSIX complience and quality with checkbashisms and shellcheck.
#
# Usage: ./lint
#

files="./goat ./setup ./lint ./libgoat.sh"
exitstatus='0'

for file in $files
do
	shellcheck -e SC1007,SC2015 --shell=sh "$file" || exitstatus='1'
	checkbashisms -npfx "$file" || exitstatus='1'
done

exit "$exitstatus"

# vim: filetype=sh softtabstop=8 shiftwidth=8 tabstop=8 noexpandtab
