#! /bin/bash -
#
# setup - A simple script for automatic installation of goat.
#
# ---
#
# Copyright (c) 2016-2018 Mateusz Piotrowski <0mp@FreeBSD.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

set -eu

# Configuration.
workingdir="$(dirname -- "$0")"
bashcompletiondir="$HOME/.bash_completion.d"
bashcompletionfile="$workingdir/goat.bash_completion"
default_goat_path="$HOME/.goat"
GOAT_PATH="$default_goat_path"
destdir="$HOME/bin"
goat="$workingdir/goat"
libgoat="$workingdir/libgoat.sh"
shellrc="$HOME/.bashrc"
tmpshellrc="$workingdir/$(basename -- "$shellrc").tmp"

errxit()
{

	printf "error: %s\n" "$*"
	trap - EXIT #TODO
	exit 1
}

usage()
{

	cat <<EOF
Usage: $0 [-d|-h|-p|-s]

Options:
    -b, --bash-completion DIR
        .Set the directory to install Bash completion files in. Disable by
         setting it to "/dev/null". Default: "$HOME/.bash_completion.d".

    -d, --destination DIR
        Set the directory to install the goat script. Remember to make sure that
        this directory is added to your \$PATH. Default: "\$HOME/bin".

    -h, --help
        Show this help message and exit.

    -p, --path DIR
        Set the GOAT_PATH value. Default: "\$HOME/.goat".

    -s, --shellrc FILE
        Set the path to the shellrc file where a line sourcing libgoat.sh will
	be added. Default: "$HOME/.bashrc"
EOF
}

while [ $# -gt 0 ]
do
	case "$1" in
		-b|--bash-completion)
			bashcompletiondir="$2"
			shift 2
			;;
		-d|--destination)
			destdir="$2"
			shift 2
			;;
		-h|--help)
			usage
			exit 0
			;;
		-p|--path)
			GOAT_PATH="$2"
			shift 2
			;;
		-s|--shellrc)
			shellrc="$2"
			shift 2
			;;
		*)
			errxit "Unknown option '$1'"
			;;
	esac
done

mkdir -p "$destdir"
mkdir -p "$GOAT_PATH"
cp "$goat" "$destdir"
cp "$libgoat" "$GOAT_PATH"

if ! grep ". $GOAT_PATH/libgoat.sh" "$shellrc" 2>/dev/null 1>&2
then
	touch "$shellrc"
	cp "$shellrc" "$tmpshellrc"
	if [ x"$default_goat_path" != x"$GOAT_PATH" ]
	then
		printf 'export GOAT_PATH="%s"\n' "$GOAT_PATH" >> "$tmpshellrc"
	fi
	cat <<EOF >>"$tmpshellrc"

# Added by goat (https://github.com/0mp/goat)
. $GOAT_PATH/libgoat.sh
EOF
	mv "$tmpshellrc" "$shellrc"
else
	printf '%s left unchanged (it looks like it is already configured)\n' \
	    "$shellrc"
fi

mkdir -p -- "$bashcompletiondir"
cp -- "$bashcompletionfile" "$bashcompletiondir/goat"

# vim: filetype=sh softtabstop=8 shiftwidth=8 tabstop=8 noexpandtab
